//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracking.Database.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug : BaseEntity
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int ProjectId { get; set; }
        public int UserId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Bug_priorities Bug_priorities { get; set; }
        public virtual Bug_Status Bug_Status { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
