//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracking.Database.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug_Status : BaseEntity
    {
        public int Id { get; set; }
        public string BugStatus { get; set; }
    }
}
