//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracking.Database.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Bugs = new HashSet<Bug>();
            this.Project_Developers = new HashSet<Project_Developers>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public int TechnologyId { get; set; }
        public bool IsActive { get; set; }
        public int ProjectStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bug> Bugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Developers> Project_Developers { get; set; }
        public virtual Project_Status Project_Status { get; set; }
        public virtual Project_Technologies Project_Technologies { get; set; }
    }
}
